gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  border: rounded
  theme:
    activeBorderColor:
      - "#c099ff"
      - bold
    inactiveBorderColor:
      - "#636da6"
    searchingActiveBorderColor:
      - "#ff966c"
      - bold
    optionsTextColor:
      - "#86e1fc"
    selectedLineBgColor:
      - "#3b4261"
    cherryPickedCommitFgColor:
      - "#fca7ea"
    cherryPickedCommitBgColor:
      - "#3b4261"
    markedBaseCommitFgColor:
      - "#ff966c"
    markedBaseCommitBgColor:
      - "#3b4261"
    unstagedChangesColor:
      - "#ff757f"
    defaultFgColor:
      - "#c8d3f5"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never

os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
