gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  border: rounded
  theme:
    activeBorderColor:
      - "#bd93f9"
      - bold
    inactiveBorderColor:
      - "#6272a4"
    searchingActiveBorderColor:
      - "#ffb86c"
      - bold
    optionsTextColor:
      - "#8be9fd"
    selectedLineBgColor:
      - "#44475a"
    cherryPickedCommitFgColor:
      - "#ff79c6"
    cherryPickedCommitBgColor:
      - "#44475a"
    markedBaseCommitFgColor:
      - "#ffb86c"
    markedBaseCommitBgColor:
      - "#44475a"
    unstagedChangesColor:
      - "#ff5555"
    defaultFgColor:
      - "#f8f8f2"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never

os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
