---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Ensure ~/.config/git exists
  ansible.builtin.file:
    path: "{{ config_dir }}/git"
    state: directory
    mode: "0755"

- name: Symlink git config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/git/config"
    dest: "{{ config_dir }}/git/config"
    state: link
    force: true

- name: Symlink global gitignore
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/git/ignore"
    dest: "{{ home_dir }}/.gitignore_global"
    state: link
    force: true

- name: Ensure ~/.ssh exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: Symlink allowed_signers
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/git/allowed_signers"
    dest: "{{ home_dir }}/.ssh/allowed_signers"
    state: link
    force: true
