Host *.prod.homelab.peterkuehne.com
  User peter
  GSSAPIAuthentication yes
  GSSAPIDelegateCredentials yes
  PasswordAuthentication no
  PreferredAuthentications gssapi-with-mic,publickey
  PubkeyAuthentication yes
  VerifyHostKeyDNS ask
