Host git.homelab.peterkuehne.com git.homelab.peterkuehne.com.
  User git
  CanonicalizeHostname no
  IdentityFile ~/.ssh/id_peter
  PasswordAuthentication no
  PubkeyAuthentication yes

Host github.com github.com.
  User git
  CanonicalizeHostname no
  IdentityFile ~/.ssh/id_peter
  PasswordAuthentication no
  PubkeyAuthentication yes
