[settings]
locked = true

[tools]
codex = "latest"
go = "latest"
node = "26"
tmux = "latest"
fzf = "latest"
eza = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
dust = "latest"
just = "latest"
lazygit = "latest"
lazydocker = "latest"
gh = "latest"
cmake = "latest"
zoxide = "latest"
direnv = "latest"
neovim = "latest"
