---
- name: Ensure bat config and syntaxes dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ config_dir }}/bat"
    - "{{ config_dir }}/bat/syntaxes"

- name: Symlink bat config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/bat/config"
    dest: "{{ config_dir }}/bat/config"
    state: link
    force: true

- name: Symlink bat syntax definitions
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/bat/syntaxes/{{ item }}"
    dest: "{{ config_dir }}/bat/syntaxes/{{ item }}"
    state: link
    force: true
  loop:
    - Just.sublime-syntax

- name: Rebuild bat syntax/theme cache
  ansible.builtin.command:
    cmd: "{{ local_bin }}/bat cache --build"
  changed_when: false
